name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/scp-action@v2
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          source: frontend/dist/
          target: /var/www/html/

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            sudo systemctl restart nginx
